name: comic_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: any
  native_pdf_view: any

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/avenger.jpg
    - asset/batman.jpg
    - asset/doga-solo.jpg
    - asset/manhwa.jpg
    - asset/raj.jpg
    - asset/scd.jpg
    - asset/hero.jpg
    - asset/crit01.jpg
    - asset/jl01.jpg
    - asset/rotr01.jpg
    - asset/sarva.jpg
    - asset/Saudangi.jpg
    - asset/doga.jpg
    - asset/ateet.jpg
    - asset/nam.jpg
    - asset/racerx.jpg
    - asset/sfl01.jpg
    - asset/sleepless.jpg
    - asset/cyborg.jpg
    - asset/SuperHeroOrigin/01.jpg
    - asset/SuperHeroOrigin/02.jpg
    - asset/SuperHeroOrigin/03.jpg
    - asset/SuperHeroOrigin/04.jpg
    - asset/SuperHeroOrigin/05.jpg
    - asset/SuperHeroOrigin/06.jpg
    - asset/SuperHeroOrigin/07.jpg
    - asset/SuperHeroOrigin/08.jpg
    - asset/SuperHeroOrigin/09.jpg
    - asset/SuperHeroOrigin/10.jpg
    - asset/SuperHeroOrigin/11.jpg
    - asset/SuperHeroOrigin/12.jpg
    - asset/IronMan_Thor/01.jpg
    - asset/IronMan_Thor/02.jpg
    - asset/IronMan_Thor/03.jpg
    - asset/IronMan_Thor/04.jpg
    - asset/IronMan_Thor/05.jpg
    - asset/IronMan_Thor/06.jpg
    - asset/IronMan_Thor/07.jpg
    - asset/IronMan_Thor/08.jpg
    - asset/IronMan_Thor/09.jpg
    - asset/IronMan_Thor/10.jpg
    - asset/IronMan_Thor/11.jpg
    - asset/IronMan_Thor/12.jpg
    - asset/IronMan_Thor/13.jpg
    - asset/IronMan_Thor/14.jpg
    - asset/IronMan_Thor/15.jpg
    - asset/IronMan_Thor/16.jpg
    - asset/IronMan_Thor/17.jpg
    - asset/IronMan_Thor/18.jpg
    - asset/IronMan_Thor/19.jpg
    - asset/IronMan_Thor/20.jpg
    - asset/IronMan_Thor/21.jpg
    - asset/IronMan_Thor/22.jpg
    - asset/IronMan_Thor/23.jpg
    - asset/IronMan_Thor/24.jpg
    - asset/IronMan_Thor/25.jpg
    - asset/C.R.I.T/01.jpg
    - asset/C.R.I.T/02.jpg
    - asset/C.R.I.T/03.jpg
    - asset/C.R.I.T/04.jpg
    - asset/C.R.I.T/05.jpg
    - asset/C.R.I.T/06.jpg
    - asset/C.R.I.T/07.jpg
    - asset/C.R.I.T/08.jpg
    - asset/C.R.I.T/09.jpg
    - asset/C.R.I.T/10.jpg
    - asset/C.R.I.T/11.jpg
    - asset/C.R.I.T/12.jpg
    - asset/JusticeLeague/01.jpg
    - asset/JusticeLeague/02.jpg
    - asset/JusticeLeague/03.jpg
    - asset/JusticeLeague/04.jpg
    - asset/JusticeLeague/05.jpg
    - asset/JusticeLeague/06.jpg
    - asset/JusticeLeague/07.jpg
    - asset/JusticeLeague/08.jpg
    - asset/JusticeLeague/09.jpg
    - asset/JusticeLeague/10.jpg
    - asset/JusticeLeague/11.jpg
    - asset/JusticeLeague/12.jpg
    - asset/JusticeLeague/13.jpg
    - asset/JusticeLeague/14.jpg
    - asset/JusticeLeague/15.jpg
    - asset/JusticeLeague/16.jpg
    - asset/JusticeLeague/17.jpg
    - asset/JusticeLeague/18.jpg
    - asset/JusticeLeague/19.jpg
    - asset/JusticeLeague/20.jpg
    - asset/RacerX/01.jpg
    - asset/RacerX/01.jpg
    - asset/RacerX/02.jpg
    - asset/RacerX/03.jpg
    - asset/RacerX/04.jpg
    - asset/RacerX/05.jpg
    - asset/RacerX/06.jpg
    - asset/RacerX/07.jpg
    - asset/RacerX/08.jpg
    - asset/RacerX/09.jpg
    - asset/RacerX/10.jpg
    - asset/RacerX/11.jpg
    - asset/Street/01.jpg
    - asset/Street/01.jpg
    - asset/Street/02.jpg
    - asset/Street/03.jpg
    - asset/Street/04.jpg
    - asset/Street/05.jpg
    - asset/Street/06.jpg
    - asset/Street/07.jpg
    - asset/Street/08.jpg
    - asset/Street/09.jpg
    - asset/Street/10.jpg
    - asset/Street/11.jpg
    - asset/Street/01.jpg
    - asset/Sleepless/01.jpg
    - asset/Sleepless/02.jpg
    - asset/Sleepless/03.jpg
    - asset/Sleepless/04.jpg
    - asset/Sleepless/05.jpg
    - asset/Sleepless/06.jpg
    - asset/Sleepless/07.jpg
    - asset/Sleepless/08.jpg
    - asset/Sleepless/09.jpg
    - asset/Sleepless/10.jpg
    - asset/Sleepless/11.jpg
    - asset/Soudangi.pdf
    - asset/Ateet.pdf
    - asset/doga.pdf



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
